// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbWP_26fRwXobYqoGOHTOXmjjcWfa-qA',
    appId: '1:351305450818:web:bc25e40e6a0bf402d334db',
    messagingSenderId: '351305450818',
    projectId: 'tripreserve-2d35a',
    authDomain: 'tripreserve-2d35a.firebaseapp.com',
    storageBucket: 'tripreserve-2d35a.firebasestorage.app',
    measurementId: 'G-J2T9HHNZW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfLlOp6uoiXDp0J1BsqOwZnP7_A7RoAQ',
    appId: '1:351305450818:android:bb9db0f15586a1e4d334db',
    messagingSenderId: '351305450818',
    projectId: 'tripreserve-2d35a',
    storageBucket: 'tripreserve-2d35a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhPcHKjQUwd9_StU7wxuMZYeR7N42n5XQ',
    appId: '1:351305450818:ios:5e4dcedd005993cfd334db',
    messagingSenderId: '351305450818',
    projectId: 'tripreserve-2d35a',
    storageBucket: 'tripreserve-2d35a.firebasestorage.app',
    iosBundleId: 'com.example.tripReserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhPcHKjQUwd9_StU7wxuMZYeR7N42n5XQ',
    appId: '1:351305450818:ios:5e4dcedd005993cfd334db',
    messagingSenderId: '351305450818',
    projectId: 'tripreserve-2d35a',
    storageBucket: 'tripreserve-2d35a.firebasestorage.app',
    iosBundleId: 'com.example.tripReserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLbWP_26fRwXobYqoGOHTOXmjjcWfa-qA',
    appId: '1:351305450818:web:803bffa59acf56b1d334db',
    messagingSenderId: '351305450818',
    projectId: 'tripreserve-2d35a',
    authDomain: 'tripreserve-2d35a.firebaseapp.com',
    storageBucket: 'tripreserve-2d35a.firebasestorage.app',
    measurementId: 'G-SK4MLWHR50',
  );
}
